export const seedProducts = [
  {
    name: 'Camiseta Engenharia de Software',
    description: 'Camiseta oficial do curso com estampa minimalista.',
    price: 69.9,
    stock: 40,
    course: 'Engenharia de Software',
    category: 'Camisetas',
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Preto', 'Branco'],
    image: '',
    featured: true,
    active: true,
  },
  {
    name: 'Caneca ADS',
    description:
      'Caneca personalizada para alunos de Análise e Desenvolvimento de Sistemas.',
    price: 34.9,
    stock: 25,
    course: 'Análise e Desenvolvimento de Sistemas',
    category: 'Canecas',
    sizes: ['Único'],
    colors: ['Branco'],
    image: '',
    featured: true,
    active: true,
  },
  {
    name: 'Caderno Direito',
    description: 'Caderno universitário com capa temática do curso.',
    price: 29.9,
    stock: 50,
    course: 'Direito',
    category: 'Material Escolar',
    sizes: ['Único'],
    colors: ['Azul', 'Preto'],
    image: '',
    featured: false,
    active: true,
  },
  {
    name: 'Mochila Administração',
    description: 'Mochila reforçada para rotina acadêmica.',
    price: 119.9,
    stock: 18,
    course: 'Administração',
    category: 'Acessórios',
    sizes: ['Único'],
    colors: ['Cinza', 'Preto'],
    image: '',
    featured: false,
    active: true,
  },
  {
    name: 'Caneca Medicina',
    description: 'Produto personalizado para o curso de Medicina.',
    price: 39.9,
    stock: 22,
    course: 'Medicina',
    category: 'Canecas',
    sizes: ['Único'],
    colors: ['Branco'],
    image: '',
    featured: true,
    active: true,
  },
  {
    name: 'Camiseta Psicologia',
    description: 'Camiseta confortável com identidade do curso.',
    price: 64.9,
    stock: 35,
    course: 'Psicologia',
    category: 'Camisetas',
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Verde', 'Preto'],
    image: '',
    featured: false,
    active: true,
  },
];
