// Definindo os dados simulados para a aplicação

import { Product, Order } from './types'

export const courses = [
  'Todos os Cursos',
  'Direito',
  'Medicina',
  'Engenharia Civil',
  'Administração',
  'Psicologia',
  'Arquitetura',
  'Ciência da Computação',
  'Enfermagem',
  'Odontologia',
]

export const categories = [
  'Todas as Categorias',
  'Camisetas',
  'Moletons',
  'Cadernos',
  'Canecas',
  'Kits Acadêmicos',
  'Acessórios',
  'Papelaria',
]

export const products: Product[] = [
  {
    id: '1',
    name: 'Camiseta UNIFOR Direito',
    price: 79.90,
    description: 'Camiseta oficial do curso de Direito da UNIFOR. Tecido 100% algodão, confortável e durável. Ideal para uso no dia a dia ou em eventos acadêmicos.',
    image: '/products/camiseta-direito.jpg',
    category: 'Camisetas',
    course: 'Direito',
    sizes: ['P', 'M', 'G', 'GG', 'XG'],
    colors: ['Branco', 'Azul Marinho', 'Preto'],
    stock: 150,
  },
  {
    id: '2',
    name: 'Moletom UNIFOR Medicina',
    price: 149.90,
    description: 'Moletom premium do curso de Medicina. Com capuz e bolso canguru, perfeito para os dias mais frios. Material de alta qualidade.',
    image: '/products/moletom-medicina.jpg',
    category: 'Moletons',
    course: 'Medicina',
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Cinza', 'Azul Marinho', 'Branco'],
    stock: 80,
  },
  {
    id: '3',
    name: 'Kit Papelaria Engenharia',
    price: 59.90,
    description: 'Kit completo de papelaria para estudantes de Engenharia. Inclui caderno, canetas, régua e estojo personalizado.',
    image: '/products/kit-engenharia.jpg',
    category: 'Kits Acadêmicos',
    course: 'Engenharia Civil',
    sizes: ['Único'],
    colors: ['Azul', 'Verde'],
    stock: 200,
  },
  {
    id: '4',
    name: 'Caneca UNIFOR Administração',
    price: 34.90,
    description: 'Caneca de porcelana personalizada do curso de Administração. Capacidade de 300ml, ideal para café ou chá.',
    image: '/products/caneca-adm.jpg',
    category: 'Canecas',
    course: 'Administração',
    sizes: ['Único'],
    colors: ['Branco', 'Preto'],
    stock: 300,
  },
  {
    id: '5',
    name: 'Caderno UNIFOR Psicologia',
    price: 44.90,
    description: 'Caderno universitário com 200 folhas, capa dura personalizada do curso de Psicologia. Folhas pautadas de alta gramatura.',
    image: '/products/caderno-psicologia.jpg',
    category: 'Cadernos',
    course: 'Psicologia',
    sizes: ['Único'],
    colors: ['Rosa', 'Roxo', 'Azul'],
    stock: 250,
  },
  {
    id: '6',
    name: 'Camiseta Polo UNIFOR',
    price: 99.90,
    description: 'Camiseta polo oficial da UNIFOR. Elegante e versátil, perfeita para eventos formais e apresentações.',
    image: '/products/polo-unifor.jpg',
    category: 'Camisetas',
    course: 'Todos os Cursos',
    sizes: ['P', 'M', 'G', 'GG', 'XG'],
    colors: ['Branco', 'Azul Royal', 'Preto'],
    stock: 120,
  },
  {
    id: '7',
    name: 'Mochila UNIFOR',
    price: 189.90,
    description: 'Mochila oficial UNIFOR com compartimento para notebook de até 15.6". Resistente à água e com múltiplos bolsos.',
    image: '/products/mochila-unifor.jpg',
    category: 'Acessórios',
    course: 'Todos os Cursos',
    sizes: ['Único'],
    colors: ['Azul Marinho', 'Preto'],
    stock: 60,
  },
  {
    id: '8',
    name: 'Kit Jaleco Enfermagem',
    price: 129.90,
    description: 'Jaleco branco de alta qualidade para estudantes de Enfermagem. Tecido resistente, fácil de lavar e passar.',
    image: '/products/jaleco-enfermagem.jpg',
    category: 'Kits Acadêmicos',
    course: 'Enfermagem',
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Branco'],
    stock: 90,
  },
  {
    id: '9',
    name: 'Squeeze UNIFOR 750ml',
    price: 39.90,
    description: 'Squeeze de alumínio personalizado UNIFOR. Mantém a bebida fresca por mais tempo. Ideal para academia e atividades ao ar livre.',
    image: '/products/squeeze-unifor.jpg',
    category: 'Acessórios',
    course: 'Todos os Cursos',
    sizes: ['Único'],
    colors: ['Prata', 'Azul', 'Preto'],
    stock: 180,
  },
  {
    id: '10',
    name: 'Camiseta Arquitetura',
    price: 79.90,
    description: 'Camiseta exclusiva do curso de Arquitetura com estampa criativa. 100% algodão penteado.',
    image: '/products/camiseta-arquitetura.jpg',
    category: 'Camisetas',
    course: 'Arquitetura',
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Branco', 'Preto', 'Cinza'],
    stock: 100,
  },
  {
    id: '11',
    name: 'Kit Estudante Computação',
    price: 89.90,
    description: 'Kit especial para estudantes de Ciência da Computação. Inclui mousepad personalizado, adesivos e camiseta.',
    image: '/products/kit-computacao.jpg',
    category: 'Kits Acadêmicos',
    course: 'Ciência da Computação',
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Preto', 'Azul'],
    stock: 70,
  },
  {
    id: '12',
    name: 'Estojo UNIFOR Premium',
    price: 29.90,
    description: 'Estojo premium com zíper duplo e múltiplos compartimentos. Design moderno com logo UNIFOR.',
    image: '/products/estojo-unifor.jpg',
    category: 'Papelaria',
    course: 'Todos os Cursos',
    sizes: ['Único'],
    colors: ['Azul Marinho', 'Preto', 'Rosa'],
    stock: 220,
  },
]

export const mockOrders: Order[] = [
  {
    id: 'ORD-001',
    items: [
      {
        product: products[0],
        quantity: 2,
        size: 'M',
        color: 'Azul Marinho',
        personalization: 'João Silva',
      },
    ],
    status: 'pending',
    customerName: 'João Silva',
    customerEmail: 'joao.silva@edu.unifor.br',
    deliveryMethod: 'campus',
    paymentMethod: 'pix',
    subtotal: 159.80,
    shipping: 0,
    total: 159.80,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'ORD-002',
    items: [
      {
        product: products[1],
        quantity: 1,
        size: 'G',
        color: 'Cinza',
      },
      {
        product: products[3],
        quantity: 2,
        size: 'Único',
        color: 'Branco',
      },
    ],
    status: 'production',
    customerName: 'Maria Santos',
    customerEmail: 'maria.santos@edu.unifor.br',
    deliveryMethod: 'delivery',
    paymentMethod: 'credit',
    address: {
      street: 'Rua das Flores',
      number: '123',
      neighborhood: 'Centro',
      city: 'Fortaleza',
      state: 'CE',
      zipCode: '60000-000',
    },
    subtotal: 219.70,
    shipping: 15.00,
    total: 234.70,
    createdAt: new Date('2024-01-14'),
  },
  {
    id: 'ORD-003',
    items: [
      {
        product: products[6],
        quantity: 1,
        size: 'Único',
        color: 'Azul Marinho',
      },
    ],
    status: 'ready',
    customerName: 'Pedro Oliveira',
    customerEmail: 'pedro.oliveira@edu.unifor.br',
    deliveryMethod: 'campus',
    paymentMethod: 'boleto',
    subtotal: 189.90,
    shipping: 0,
    total: 189.90,
    createdAt: new Date('2024-01-13'),
  },
  {
    id: 'ORD-004',
    items: [
      {
        product: products[4],
        quantity: 3,
        size: 'Único',
        color: 'Rosa',
        personalization: 'Ana Costa',
      },
    ],
    status: 'shipped',
    customerName: 'Ana Costa',
    customerEmail: 'ana.costa@edu.unifor.br',
    deliveryMethod: 'delivery',
    paymentMethod: 'pix',
    address: {
      street: 'Av. Beira Mar',
      number: '456',
      complement: 'Apt 1001',
      neighborhood: 'Meireles',
      city: 'Fortaleza',
      state: 'CE',
      zipCode: '60165-121',
    },
    subtotal: 134.70,
    shipping: 15.00,
    total: 149.70,
    createdAt: new Date('2024-01-12'),
  },
  {
    id: 'ORD-005',
    items: [
      {
        product: products[7],
        quantity: 1,
        size: 'M',
        color: 'Branco',
      },
    ],
    status: 'delivered',
    customerName: 'Lucas Ferreira',
    customerEmail: 'lucas.ferreira@edu.unifor.br',
    deliveryMethod: 'campus',
    paymentMethod: 'credit',
    subtotal: 129.90,
    shipping: 0,
    total: 129.90,
    createdAt: new Date('2024-01-10'),
  },
]
